/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SipAutomationsRouteImport } from './routes/sip-automations'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const SipAutomationsRoute = SipAutomationsRouteImport.update({
  id: '/sip-automations',
  path: '/sip-automations',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/ledger': typeof LedgerRoute
  '/markets': typeof MarketsRoute
  '/sip-automations': typeof SipAutomationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/ledger': typeof LedgerRoute
  '/markets': typeof MarketsRoute
  '/sip-automations': typeof SipAutomationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/ledger': typeof LedgerRoute
  '/markets': typeof MarketsRoute
  '/sip-automations': typeof SipAutomationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/ledger' | '/markets' | '/sip-automations'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/ledger' | '/markets' | '/sip-automations'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/ledger'
    | '/markets'
    | '/sip-automations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LedgerRoute: typeof LedgerRoute
  MarketsRoute: typeof MarketsRoute
  SipAutomationsRoute: typeof SipAutomationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sip-automations': {
      id: '/sip-automations'
      path: '/sip-automations'
      fullPath: '/sip-automations'
      preLoaderRoute: typeof SipAutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LedgerRoute: LedgerRoute,
  MarketsRoute: MarketsRoute,
  SipAutomationsRoute: SipAutomationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
